/**:
  ros__parameters:
    axis_id: "x"
    driver_mode: "hardware"
    serial_number: "45456044"
    serial_port: ""
    min_position: 0.0
    max_position: 300.0
    default_velocity: 5.0
    default_acceleration: 1.0
    movement_timeout: 60.0
    homing_timeout: 180.0
    state_publish_rate_hz: 10.0
