camera_params:
  # GUID of camera which you can get using `arv-tool`.
  guid: 'IDS Imaging Development Systems GmbH-1409f4a43375-4104401781'
  # RGB8, BGR8, etc.
  pixel_format: 'RGB8'
  # usb3vision or gigevision
  driver: 'usb3vision'
  # Arbitrary name to identify camera and used for ROS node names
  cameraname: 'promoc_camera'
  pixelsize: 2.4 # in um (Sony IMX183: 2.40 µm)
  magnification: 1 
  camera_axis_1: 'x'
  camera_axis_2: 'y'
  camera_axis_1_angle: 0                # Starting from normal 'x' in math. positive direction
  camera_axis_2_angle: '+'              # '+' -> 90 degree; '-' -> -90 degree 
  subscription_topic: '/promoc/assembly_camera/stream0/image_raw'

exposure_time:
  srv_client_name: '/promoc/assembly_camera_controller/set_exposure_time'
  srv_type: 'pm_genicam_controller_interfaces/srv/SetExposureTime'
  min_val: 27.1
  max_val: 2000012.4

camera_info:
  image_width: 2048  
  image_height: 1536
  camera_name: assembly_camera_stream0
  camera_matrix:
    rows: 3
    cols: 3
    data: [1500.0, 0.0, 1024.0,  # Adjusted for 2048x1536
          0.0, 1500.0, 768.0,
          0.0, 0.0, 1.0]
  distortion_model: plumb_bob
  distortion_coefficients:
    rows: 1
    cols: 5
    data: [0.0, 0.0, 0.0, 0.0, 0.0]
  rectification_matrix:
    rows: 3
    cols: 3
    data: [1.0, 0.0, 0.0,
          0.0, 1.0, 0.0,
          0.0, 0.0, 1.0]
  projection_matrix:
    rows: 3
    cols: 4
    data: [1500.0, 0.0, 1024.0, 0.0, 
          0.0, 1500.0, 768.0, 0.0,
          0.0, 0.0, 1.0, 0.0]


# see https://github.com/FraunhoferIOSB/camera_aravis2?tab=readme-ov-file#how-to-dynamically-change-camera-parameters
# for more info
dynamic_parameters:
  - FeatureName: AcquisitionFrameRate
    Type: float
    Min: 1.0
    Max: 19.8  # Max framerate for IDS U3-3800CP
    Description: Controls the acquisition rate (in Hertz) at which the frames are captured.
  - FeatureName: ExposureTime
    Type: float
    Min: 62.7  # From controller log: Min: 62.666666666666664
    Max: 977178.9  # From controller log: Max: 977178.9166666666
    Description: Exposure time in microseconds.