camera_params:
  # GUID of camera which you can get using `arv-tool`.
  guid: 'IDS Imaging Development Systems GmbH-1409f4a43375-4104401781'
  # RGB8, BGR8, etc.
  pixel_format: 'RGB8'
  # usb3vision or gigevision
  driver: 'usb3vision'
  # Arbitrary name to identify camera and used for ROS node names
  cameraname: 'assembly_camera'
  pixelsize: 2.2 # in um
  magnification: 1 
  sensor_resolution_h: 5536
  sensor_resolution_v: 3692
  camera_axis_1: 'x'
  camera_axis_2: 'y'
  camera_axis_1_angle: 0                # Starting from normal 'x' in math. positive direction
  camera_axis_2_angle: '+'              # '+' -> 90 degree; '-' -> -90 degree 
  subscription_topic: '/promoc/assembly_camera/stream0/image_raw'

exposure_time:
  srv_client_name: '/promoc/assembly_camera_controller/set_exposure_time'
  srv_type: 'pm_genicam_controller_interfaces/srv/SetExposureTime'
  min_val: 27.1
  max_val: 2000012.4

camera_info:
  image_width: 2448
  image_height: 2048
  camera_name: assembly_camera_stream0
  camera_matrix:
    rows: 3
    cols: 3
    data: [1778.591345, 0.000000, 964.276439,
          0.000000, 1789.714953, 804.364652,
          0.000000, 0.000000, 1.000000]
  distortion_model: plumb_bob
  distortion_coefficients:
    rows: 1
    cols: 5
    data: [-0.149383, 0.142808, 0.002512, -0.003641, 0.000000]
  rectification_matrix:
    rows: 3
    cols: 3
    data: [ 0.969314, -0.024000, 0.244652,
            0.025128, 0.999683, -0.001489,
            -0.244539, 0.007591, 0.969610]
  projection_matrix:
    rows: 3
    cols: 4
    data: [ 2720.246602, 0.000000, 710.195835, 0.000000,
            0.000000, 2720.246602, 798.603073, 0.000000,
            0.000000, 0.000000, 1.000000, 0.000000]

# see https://github.com/FraunhoferIOSB/camera_aravis2?tab=readme-ov-file#how-to-dynamically-change-camera-parameters
# for more info
dynamic_parameters:
  - FeatureName: AcquisitionFrameRate
    Type: float
    Min: 1.0
    Max: 50.0
    Description: Controls the acquisition rate (in Hertz) at which the frames are captured.
  - FeatureName: ExposureTime
    Type: float
    Description: Exposure time in milliseconds.
  - FeatureName: BinningHorizontal
    Type: int
    Min: 1
    Max: 2
    Description: Horizontal binning factor.
  - FeatureName: BinningVertical
    Type: int
    Min: 1
    Max: 2
    Description: Vertical binning factor.
  - FeatureName: Width
    Type: int
    Min: 256
    Max: 5536
    Description: Width of the image in pixels.
  - FeatureName: Height
    Type: int
    Min: 256
    Max: 3692
    Description: Height of the image in pixels.
