
mover_node:
  ros__parameters:
    node_name: 'mover_node'
    debug_mode: false
    # Movement boundaries
    x_min: 0.055
    x_max: 0.420
    y_min: -0.055
    y_max: 0.180
    z_min: 0.000
    z_max: 0.004
    # Tolerances
    xy_tolerance: 0.001
    six_d_tolerance: 0.001
    # Standard velocity parameters
    standard_velocities:
      xy_vel: 1.00
      z_vel: 0.10
      rx_vel: 0.10
      ry_vel: 0.10
      rz_vel: 0.10
      xy_max_accel: 5.00
      z_max_accel: 1.00