lts300_devices:
  device1:
    executable: lts300_service_node 
    serial_number: '45318394'
    node_name: 'lts300_z_axis'
    other_axes: [lts300_camera_x_axis]
  #device2:
    #executable: lts300_service_node 
    #serial_number: '45318395'
    #node_name: 'lts300_camera_x_axis'
    #other_axes: [lts300_z_axis]
    
mover_node:
  move_area_parameters:
    x_min: 0.055
    x_max: 0.420
    y_min: -0.055
    y_max: 0.180
    z_min: 0.000
    z_max: 0.004

remote_connection:
  user: 'admin'
  host: '10.145.4.63'
  ros_domain_id: '13'

namespace: 'promoc_assembly'

