# Mover Node Parameters
mover_node:
  ros__parameters:
    node_name: 'mover_node'
    x_min: 0.055
    x_max: 0.420
    y_min: -0.055
    y_max: 0.180
    z_min: 0.000
    z_max: 0.004

# LTS300 Z-Axis Parameters
lts300_z_axis:
  ros__parameters:
    serial_port: '/dev/ttyUSB0'
    serial_number: '45407924'
    collision_threshold: 200.0
    device_units_per_mm: 409600.0

# LTS300 X-Axis Parameters
lts300_x_axis:
  ros__parameters:
    serial_port: '/dev/ttyUSB1'
    serial_number: '45456044'
    collision_threshold: 30.0
    device_units_per_mm: 409600.0