lts300_devices:
  device1:
    package: 'linear_axis_nodes'
    executable: lts300_service_node_linux
    serial_port: '/dev/ttyUSB0'
    serial_number: '45407924'
    node_name: 'lts300_z_axis'
  device2:
    package: 'linear_axis_nodes'
    executable: lts300_service_node_linux 
    serial_number: '45456044'
    serial_port: '/dev/ttyUSB1'
    node_name: 'lts300_x_axis'
    
mover_node:
  package: 'planar_motor_nodes'
  executable: mover_service_node
  node_name: 'mover_node'
  move_area_parameters:
    x_min: 0.055
    x_max: 0.420
    y_min: -0.055
    y_max: 0.180
    z_min: 0.000
    z_max: 0.004

#remote_connection:
  #user: 'admin'
  #host: '10.145.4.39'
  #ros_domain_id: '13'

namespace: 'promoc_assembly'

