# Global configuration
namespace: 'promoc_assembly'

# Planar motor configuration
mover_node:
  package: 'planar_motor_nodes'
  executable: 'mover_service_node'
  node_name: 'mover_node'
  move_area_parameters:
    x_min: 0.055
    x_max: 0.420
    y_min: -0.055
    y_max: 0.180
    z_min: 0.000
    z_max: 0.004

# Linear axis devices configuration
lts300_devices:
  z_axis:
    package: 'linear_axis_nodes'
    executable: 'lts300_service_node'
    serial_port: '/dev/ttyUSB0'
    serial_number: '45407924'
    node_name: 'lts300_z_axis'
    parameters:
      collision_threshold: 10.0
      device_units_per_mm: 409600.0
  
  x_axis:
    package: 'linear_axis_nodes'
    executable: 'lts300_service_node'
    serial_port: '/dev/ttyUSB1'
    serial_number: '45456044'
    node_name: 'lts300_x_axis'
    parameters:
      collision_threshold: 10.0
      device_units_per_mm: 409600.0

# Remote connection settings (commented out for local development)
# remote_connection:
#   user: 'admin'
#   host: '10.145.4.39'
#   ros_domain_id: '13'

