system:
  ros__parameters:
    driver_mode: "hardware"
    enable_camera: true
    enable_x_axis: true
    enable_z_axis: true
    enable_planar_motor: true
    enable_system_controller: true
    config_paths:
      camera: "camera_nodes/config/camera.yaml"
      x_axis: "linear_axis_nodes/config/x_axis.yaml"
      z_axis: "linear_axis_nodes/config/z_axis.yaml"
      planar_motor: "planar_motor_nodes/config/planar_motor.yaml"
      system_controller: "promoc_core/config/system_controller.yaml"
