# rqt-friendly synchronous wrapper around the cancellable EstimateTargetTilt action.
float64 center_z_mm
float64 half_range_mm
float64 step_mm
uint32 frames_per_position
bool fit_field_curvature
bool return_to_center
---
bool accepted
uint8 status
string status_message
float64 tilt_x_deg
float64 tilt_y_deg
float64 uncertainty_x_deg
float64 uncertainty_y_deg
float64 detection_limit_x_deg
float64 detection_limit_y_deg
float64 center_focus_z_mm
float64 surface_rms_um
uint32 roi_total
uint32 roi_valid
float64 x_span_fraction
float64 y_span_fraction
bool tilt_x_detectable
bool tilt_y_detectable
bool within_tolerance_x
bool within_tolerance_y
bool resolution_limited_x
bool resolution_limited_y
string decision_x
string decision_y
float64 surface_mae_um
float64 surface_median_abs_um
float64 surface_max_abs_um
uint32 roi_surface_inliers
uint32 roi_rejected_focus
uint32 roi_rejected_spatial
uint32 roi_rejected_surface
uint32 roi_robust_outliers
float64 mean_peak_uncertainty_um
float64 median_peak_uncertainty_um
string evaluation_directory
float64[4] target_bbox_normalized
float64 target_coverage_fraction
float64 baseline_x_mm
float64 baseline_y_mm
uint32 candidate_roi_count
uint32 structurally_valid_candidate_count
uint32 focus_valid_roi_count
uint32 selected_roi_count
uint32 surface_inlier_count
float64 design_condition_number
