/**:
  ros__parameters:
    driver_mode: "hardware"
    xbot_id: 0
    publish_rate: 10.0 # Hz
    pmc_ip: "192.168.10.100"
    auto_activate: true
    movement_timeout: 10.0
    mock_xbot_count: 1

    # Movement boundaries
    x_min: 0.055
    x_max: 0.420
    y_min: 0.055
    y_max: 0.180
    z_min: 0.000
    z_max: 0.004

    # Tolerances
    xy_tolerance: 0.001
    six_d_tolerance: 0.001

    # Default speed profile in SI units.
    default_xy_vel: 0.05
    default_xy_max_accel: 0.2
    default_z_vel: 0.01
    default_z_max_accel: 0.05
    default_rx_vel: 0.17453292519943295
    default_ry_vel: 0.17453292519943295
    default_rz_vel: 0.2617993877991494
